name: Deploy Gatsby Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [contentful]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verify Node.js version
        run: node -v

      - name: Verify npm version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> $GITHUB_ENV
          echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CONTENTFUL_HOST=${{ secrets.CONTENTFUL_HOST }}" >> $GITHUB_ENV  # Only if using a custom host
        shell: bash

      - name: Verify environment variables
        run: |
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID"
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN"
          echo "CONTENTFUL_HOST=$CONTENTFUL_HOST"

      - name: Build Gatsby site
        run: npm run build

      - name: Deploy to Hostinger
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          sudo apt-get install lftp
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -R ./public /public_html/blog"
